### ISSUE TITLE
Sinch service crash and wouldn't start on android lollipop

### ISSUE THREAD

**Issue by Remix2100** [sinch/android-messaging-tutorial#6]
I'm developing a messaging app using sinch and it' s working so good while testing it on all android devices except the ones running android lollipop.

Is there any reason for that ?,and if there is a problem on your side...can you fix it ?

**Comment by Remix2100** [comment]
The solution is here http://stackoverflow.com/questions/27659451/sinch-force-close-on-application-start-on-android-lollipop/28365993#28365993

**Comment by michelebenolli** [comment]
this is not properly a solution... I can not build every time the app in release mode..

**Comment by Remix2100** [comment]
I tried every other way and that was the only solution, you can probably go and argue with samsung but they won't listen because they think that when they do this it makes them special.
